# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%

comment:
  layout: "header, components"
  require_changes: false
  branches: null
  behavior: default

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: frontend
      name: frontend
      paths:
        - mdadash/frontend/src/
    - component_id: backend
      name: backend
      paths:
        - mdadash/backend/
